spring.application.name=haishi-admin
server.port=8888
server.servlet.context-path=/api

# 日志配置
logging.level.root=info
logging.level.org.springframework.web=info
logging.level.com.haishi=debug
logging.file.path=logs
logging.file.name=haishi-admin
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.total-size-cap=1GB

# jackson配置
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.jackson.locale=zh_CN

Traceback (most recent call last): File "class/acme_v2.py", line 1400, in apply_cert self.auth_domain(index) File "class/acme_v2.py", line 645, in auth_domain 'valid', 'invalid']) File "class/acme_v2.py", line 678, in check_auth_status json.dumps(a_auth) StopIteration: 验证失败,没有解析域名,或解析未生效! >>>> {"identifier": {"type": "dns", "value": "console.a2site.xyz"}, "status": "invalid", "expires": "2024-05-08T08:48:06Z", "challenges": [{"type": "http-01", "status": "invalid", "error": {"type": "urn:ietf:params:acme:error:dns", "detail": "DNS problem: NXDOMAIN looking up A for console.a2site.xyz - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for console.a2site.xyz - check that a DNS record exists for this domain", "status": 400}, "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/345292165127/cXrHzw", "token": "G2JMXTWlP0cWfl_KLYp4dP9LG_jv-Kn0C_I1PBNxfOU", "validated": "2024-05-01T08:48:09Z"}]}